### PR TITLE
recipe updates

### PR DESCRIPTION
**Pull request by RobinD42**
Update nightly build recipe to be more in line with the recent changes in the pymeep-feedstock recipe.

### CODE REVIEW

**Comment by oskooi** [comment]
I'm not sure why the Travis tests are no longer working. Looking at the commit history of this repo, it's seems that Aug. 13 was the last time the Travis tests ran.

**Comment by RobinD42** [comment]
I was wondering if it is only set up to trigger for commits to master, but I don't have access to check the settings.

**Comment by oskooi** [comment]
I just updated a setting on Travis. Try pushing a new commit to see if it will trigger the Travis tests.

**Comment by RobinD42** [comment]
Looks like it still isn't triggering.

**Comment by oskooi** [comment]
Just migrated this repo from travis-ci.org to travis-ci.com. Try committing again.

**Comment by oskooi** [comment]
From the Travis logs, it seems that the last test that was run for Python 3.8 before the line `TESTS FAILED: pymeep-1.15.1.dev-nompi_py38_nomklh20c3811_123.tar.bz2` is `python/tests/n2f_periodic.py`. The results generated by `n2f_periodic.py` on the lines prefixed by `norm:,` are correct/expected.  Thus, it is strange that the test suite suddenly dies right after this one test is completed and before the next test (`oblique_source.py`) begins.

**Comment by oskooi** [comment]
Perhaps we first need to update the [MPB recipe](https://github.com/Simpetus/mpb-nightly-recipe) which depends on BLAS and LAPACK?

**Comment by RobinD42** [comment]
> Perhaps we first need to update the [MPB recipe](https://github.com/Simpetus/mpb-nightly-recipe) which depends on BLAS and LAPACK?

Perhaps, but the build and tests work fine on my linux VMs (I've tried ubuntu 18.04 and 16.04 so far) so I don't think we can lay the blame on the available MPB dev build.

**Comment by RobinD42** [comment]
"[It's working!!](https://www.youtube.com/watch?v=AXwGVXD7qEQ)" 

😃

**Comment by oskooi** [comment]
Looks like this is ready to go.

**Comment by RobinD42** [comment]
Yep. Go ahead and merge it. (I don't have write access.)

**Comment by oskooi** [comment]
Was the only issue for Python 3.8 the use of `parallel` in the serial builds which had to be removed?

I will merge this. Should we also try removing the conda-smithy template files from the recipe just to see if the build can pass without them (as they were originally)?

**Comment by RobinD42** [comment]
> Was the only issue for Python 3.8 the use of parallel in the serial builds which had to be removed?

Yes. I think removing parallel was the key change that let it work again, although there may be some bits of other attempts remaining.

I'll experiment with removing the conda-smithy files, but IIRC there were issues before the testing steps that using those files fixed.

**Comment by RobinD42** [comment]
It looks like the build done for the PR merge has had the same problem again with the Py3.8 nompi build. See https://travis-ci.com/github/Simpetus/pymeep-nightly-recipe/builds/186751242.

I'll spend a little more time on this and see if I can find another cause or workaround.

**Comment by oskooi** [comment]
Ok. As I mentioned previously, it might be worthwhile to first make sure that the [Conda package for the MPB nightly build](https://github.com/Simpetus/mpb-nightly-recipe) is working since its tests are failing on Travis.

**Pull request merged**
