### PR TITLE
Update recipe again

### PR DESCRIPTION
**Pull request by RobinD42**
* Add fortran details to `conda_build_config.yaml` to avoid dependency conflicts.
* Remove some hacks from the last PR

### CODE REVIEW

**Comment by oskooi** [comment]
Unfortunately, just the one build is again failing: Python 3.8, serial, no mkl.

From the Travis log, the build failure happens right after `python/tesets/n2f_periodic.py` finishes (which is showing the correct output). It's not clear what the source of the failure is because it does not seem to be this particular test.

**Comment by oskooi** [comment]
Here's something to try: make sure that the `--with-openmp` flag is *not* used during the compile stage (which seems to be the case) and, as an additional measure, disable multithreading by setting the env variable `OMP_NUM_THREADS=1` when running the tests. The failing test `n2f_periodic.py` involves a function `get_farfields_array` which may be triggering the error because of an issue related to multithreading.

**Comment by RobinD42** [comment]
Ok, I'll look into that.

**Comment by oskooi** [comment]
If adding `OMP_NUM_THREADS=1` is still failing, we should remove `parallel` completely since it was just meant to provide some speedup for serial runs but seems unreliable on Travis.

**Comment by RobinD42** [comment]
Yep, I was thinking that too.

**Comment by oskooi** [comment]
Looks like the failing `n2f_periodic.py` test is now passing for the Python 3.8, serial, no mkl, build environment. Still waiting for the other tests to finish but at least we now know what was causing this test to fail.

**Comment by RobinD42** [comment]
If it succeeds a 2nd time then I'll be happy. It passed once with the last PR after switching away from using parallel, and then failed again after merging the PR.

**Comment by RobinD42** [comment]
Okay, I think I'm done with this PR. Go ahead and merge after the remaining builds pass.

**Pull request merged**
